# -*- coding: utf-8 -*-
"""Nadia Amalia_1800015099_Variabel_&_Tipe_Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sFIQ9_GegaeOYJE9lsbn1058anZlslYg

![alt text](https://drive.google.com/uc?id=1oZeOBAOozxedBi-jq-LzN8BQd0NB7Ocy
)

Assalamualaikum warahmatullahi wabarakatuh.

***Robbi Zidni Ilma Warzuqni Fahma***

Semoga Allah memberi kemudahan untuk kita memperoleh ilmu yang bermanfaat.

Ini adalah notebook yang disusun untuk **Kelas Dasar Pejuang Data Sains 2.0** .

Ini adalah **Notebook Variabel & Tipe Data**:

## **Hasil Yang Ingin Dicapai**
1. Memahami input dan output pada python
2. Mengenal dan memahami variabel dan tipe data pada python
3. Mengenal dan memahami struktur data pada python

### ***!!!***

***Sebelum memulai mempelajari notebook ini, jangan lupa untuk menyalinnya di drive masing-masing ya.***

### ***!!!***

##  **Input & Output pada Pyhton**

Kita akan memulai dengan mencoba mengenal dan memahami proses input dan output pada bahasa pemrograman python. Sebuah Program terdiri dari Input, Proses dan Output

**Membuat input dengan fungsi input()**

format input() :
input(*object, nilai)

Sebuah input dapat dikelola berdasarkan tipe datanya :

* input() : nilai berupa string

* str(input()) : nilai berupa string

* int(input()) : nilai berupa integer

* float(input()) : nilai berupa float

* bool(input()) : nilai berupa boolean

**Untuk menampilkan Output dengan fungsi print()**

format print() :
print(*object, sep=' ', end='\n', file=sys.stdout, flush=False/True)
"""

# Membuat input bertipe data string (str)
nama = input("Nama : ")
umur = input("Umur : ")
alamat = input("Alamat : ")

print(nama)
print(umur)
type(nama)

# Membuat input bertipe data integer (int)
angka1 = int(input())
print(angka1)

# Membuat input beripe data float
angka2 = float(input())
print(angka2)

"""Saatnya kamu mencoba!!!"""

Watashi = input("watashi : ")
Old = input("old : ")
Daerah = input( "Daerah : ")

print(Watashi)
print(Old)
print(Daerah)

angka5 = int(input())
print(angka5)

nomor = float(input())
print (nomor)

"""**Menampilkan Output cara pertama**

"""

print("Nama saya"+" "+ nama + " " + "yang berumur"+ " " + umur + " " + "dan bertempat tinggal di"+ " " + alamat)

"""Saatnya kamu mencoba!!!"""

print('nama saya Nadia'+" " +'dari Universitas Ahmad Dahlan'+ " "+'Yogyakarta')

"""**Menampilkan Output cara kedua**

Menggunakan fungsi format()
"""

txt1 = "Nama saya {nama}, Saya berumur {umur}".format(nama = "Dahlan", umur = 18)
txt1

txt2 = "Nama saya {0}, Saya berumur {1}".format("Dahlan",18)
txt2

txt3 = "Nama saya {}, Saya berumur {}".format("Dahlan",18)
txt3

"""Saatnya kamu mencoba!!!"""

txt4 = "Halo-halo {kota}, Ibu Kota {lagu}".format(kota = "Bandung", lagu = "periangan")
txt4

txt5 = "Halo-halo {0}, Ibu Kota {1}".format("Bandung","periangan")
txt5

txt6 = "Halo {} plus {}".format("warga",62)
txt6

"""**Menampilkan Output cara ketiga**

Menggunakan simbol %

* %c : mencetak karakter

* %s : mencetak data menjadi string

* %i, %d : mencetak angka desimal bertanda
* %u : mencetak angka desimal tak bertanda
* %x, %X : mencetak angka heksa dengan huruf kecil %x atau besar %X
* %f : mencetak angka real berkoma
* %e, %E : mencetak tanda eksponensial dengan huruf kecil %e atau besar %E
* %g, %G : fungsi hampir sama dengan %f dan %e hanya saja pencetakan angak di belakang koma lebih pendek
"""

print("Nama saya %s yang berumur %s dan bertempat tinggal di %s" %(nama, umur, alamat))

"""Saatnya kamu mencoba!!!"""

print("Nama saya %s yang berumur %s dan bertempat tinggal di %s" %(Watashi, Old, Daerah))

"""## **Variabel, Tipe Data, Dan Konversinya**

Selanjutnya kita akan mengenal variabel dan tipe data pada python. Ini merupakan dasar yang harus dipahami di awal sebelum melanjutkan ke materi berikutnya. Pertama kita akan memahami bagaimana sebuah variabel dituliskan dalam python.

### Variabel

*   Variabel merupakan tempat penyimpanan data atau nilai
*   Sebuah variabel dalam python bisa diisi dengan berbagai tipe data
*   Nama sebuah variabel tidak bisa diawali dengan angka/numerik
*   Nama sebuah variabel selain keyword dari bahasa python
*   Format variabel : Nama_variabel = data/nilai

**Membuat sebuah variabel dengan berbagai tipe data Python**
"""

var1 = 'Assalamualaikum Dunia!' #String
var2 = 1234567890 # int
var3 = 0.123456789 # float
var4 = False #bool
var5 = 1j+1 #complex

"""Buat variabelmu sendiri di bawah ini ya!"""

var7=' belajar bersama Pejuang Data'
print(var7)

var10=' Jangan menyerah'
print(var10)

"""**Memanggil variabel dan menampilkan**

Kamu dapat memanggil variabel hanya dengan menuliskan variabel yang sudah kamu buat di atas dan menjalankan cellnya
"""

var1

"""Saatnya kamu mencoba!!!"""

var10

"""Selain itu, kamu juga bisa mencetak, atau menampilkan variabel yang sudah kamu buat dengan cara memasukkan syntak **print(*variable*)**. Contohnya sebagai berikut:"""

print(var1) #tipe data string
print(var2) #tipe data integer
print(var3) #tipe data float
print(var4) #tipe data boolean
print(var5) #tipe data Complex

"""Sekarang, tampilkan variabelmu sendiri:"""

var12 = 'Semangat!' #String
var7 = 2736593 #int
var8 = 0.00000089 #float
var9 = True #bool
var10 = 1j+5 #complex

#Mencetak variabel punya kamuuch

print(var12) #tipe data string
print(var7) #tipe data integer
print(var8) #tipe data float
print(var9) #tipe data boolean
print(var10) #tipe data Complex

"""Note: Tanda Pagar (#) berfungsi sebagai komentar, tidak dijalankan sebagai perintah pemrograman

### Tipe Data

Tipe data adalah kumpulan tipe yang dapat kamu temukan di semua data. Dengan memahami tipe data, kamu dapat menentukan nilai data yang dimiliki dari data tersebut.

**Mengenal Beberapa Tipe Data Pada Python:**
1.   String
2.   Number (Integer, Float, Complex, Boolean)

**Melihat Tipe Data dari Suatu Variabel**

Kamu bisa melihat tipe variabel yang sudah kamu buat,apakah tipe data kamu adalah int, float, boolean, string, dll menggunakan fungsi **type(*variabel*)**, sebagai berikut:
"""

type(var1)

"""Sekarang coba kamu cek tipe variabel yang udah kamu buat!!!"""

print(var12,'Tipe data var1:', type(var12))
print(var7,'Tipe data var2:', type(var7))
print(var8,'Tipe data var3:', type(var8))
print(var9,'Tipe data var4:', type(var9))
print(var10,'Tipe data var5:', type(var10))

"""Kok yang tampil cuma yang terakhir!!!, ya emang begitu, python hanya akan ngejalanin line terakhir untuk ditampilin, biar tampil semua maka kita print aja seperti di bawah ini:"""

print(var1,'Tipe data var1:', type(var1))
print(var2,'Tipe data var2:', type(var2))
print(var3,'Tipe data var3:', type(var3))
print(var4,'Tipe data var4:', type(var4))
print(var5,'Tipe data var5:', type(var5))

"""### Konversi Tipe Data

Capek gag sih, bikin data baru mulu untuk sebuah tipe data yang berbeda. Kalo capek ya udah, rehat dulu. Nah ada cara lain sih, yaitu dengan mengubah tipe data yang udah kita miliki menjadi tipe data yang kita inginkan. Kadang gag harus ganti kan, cukup komit untuk merubah hal-hal yang sudah ada sesuai keinginan kita. OK Lanjuut.

Intinya mah misal kita punya variabel tipenya int tapi kita butuh variabel itu jadi float ya kita bisa konversi, gimana caranya?

Pake fungsi donk, fungsinya macem-macem, tapi intinya adalah fungsinya bernama tipe data baru yang ingin kita buat kemudian inputnya adalah tipe data yang mau kita ubah. Begono.

Bingung?
Ini lho macam-macam fungsinya:

Fungsi untuk mengubah/konversi tipe data:

a. int() : untuk mengubah menjadi integer

b. float() : untuk mengubah menjadi float

c. str() : untuk mengubah menjadi string

d. bool() : untuk mengubah menjadi boolean

e. long() : untuk mengubah menjadi integer panjang

f. chr() : untuk mengubah menjadi karakter

g. bin() : untuk mengubah menjadi bilangan biner

h. hex() : untuk mengubah menjadi bilangan Heksadesimal

i. oct() : untuk mengubah menjadi bilangan okta

Contohnya ini ya:
"""

number = 10
print("data =", number, ", type =", type(number))

# Mengkonversi tipe data integer
kon_float = float(number)
kon_str = str(number)
kon_bool = bool(number) #False jika integer = 0, lainnya True (perhatikan hasilnya)


# Melihat data yang telah dikonversi
print("data = ", kon_float , ",type =", type(kon_float))
print("data = ", kon_str , ",type =", type(kon_str))
print("data = ", kon_bool , ",type =", type(kon_bool))

"""Saatnya kamu mencoba!!!"""

number = 19
print("data =", number, ", type =", type(number))

kon_float = float(number)
kon_str = str(number)
kon_bool = bool(number) #False jika integer = 0, lainnya True (perhatikan hasilnya)
kon_bin = bin(number)

print("data = ", kon_float , ",type =", type(kon_float))
print("data = ", kon_str , ",type =", type(kon_str))
print("data = ", kon_bool , ",type =", type(kon_bool))
print("data = ", kon_bin , ",type =", type(kon_bin))

"""## **Berbagai Struktur Data di Python**

### **List**

List adalah jenis kumpulan data terurut (ordered sequence), dan merupakan salah satu variabel yang sering digunakan pada Python. Serupa, namun tak sama dengan array pada bahasa pemrograman lainnya. Bedanya, elemen List pada Python tidak harus memiliki tipe data yang sama. Mendeklarasikan List cukup mudah dengan kurung siku dan elemen yang dipisahkan dengan koma.

*Setiap data di dalamnya dapat diakses dengan indeks yang dimulai dari 0.*
"""

a = [1, 2.2, 'python']
a

"""Bikin versimu sendiri donk, jangan baca doank! heheheh"""

n = [ 5, 4, 6.8, 'Pelangi']
n

"""Python mengenal slicing operator [ ] yang dapat melakukan ekstraksi sebuah item atau beberapa item yang berada dalam range tertentu pada tipe data urutan (sequences), misalnya list, string dan tuple. Beberapa tipe urutan juga mendukung "extended slicing" dengan parameter ketiga berupa "step".

* x[0] artinya mengambil elemen paling awal, dengan  index 0 dari List x.

* x[5] artinya mengambil elemen dengan index 5 dari List x.

* x[-1] artinya mengambil elemen dengan index paling belakang ke-1 dari List x.

* x[3:5] artinya membuat list dari anggota elemen List x dengan index 3 hingga sebelum index 5 (tidak termasuk elemen dengan index 5, dalam hal ini hanya index 3-4).

* x[:5] artinya membuat list dari anggota elemen List x paling awal hingga sebelum index 5 (tidak termasuk elemen dengan index 5, dalam hal ini hanya index 0-4).

* x[-3:] artinya membuat list dari anggota elemen List x mulai index ke-3 dari belakang hingga paling belakang.

* x[1:7:2] artinya membuat list dari anggota elemen List x dengan index 1 hingga sebelum index 7, dengan "step" 2 (dalam hal ini hanya index 1, 3, 5).
"""

x = [5,10,15,20,25,30,35,40]
print(x[5])
print(x[-1])
print(x[3:5])
print(x[:5])
print(x[-3:])
print(x[1:7:2])

"""Cobain ya!"""

x = [1,2,3,4,5,6,7,8,9,10]
print(x[5])
print(x[-1])
print(x[3:5])
print(x[:5])
print(x[-3:])
print(x[1:7:2])

"""Elemen pada list dapat diubah atau ditambahkan. Misalnya untuk melakukan perubahan kemudian penambahan:"""

#Mengganti elemen
x = [1,2,3]
x[2]=4
print (x)

#Menambah elemen
x = [1,2,3]
x[2]=4
x.append(5) #append artinya menambah
print(x)

"""Saatnya kamu mencoba!





"""

y = [7,8,9]
y[1]=11
print(y)

y = [7,8,9]
y[1]=11
y.append(10)
print(y)

"""Untuk menghapus item pada list, gunakan fungsi del. *Ingat bahwa Indeks Python dimulai dari 0*:"""

binatang = ['kucing', 'rusa', 'badak', 'gajah']
del binatang[2]
print(binatang)

"""Do it by yourself"""

tanaman = ['mawar', 'melati', 'tulip', 'anggrek']
del tanaman [1]
print(tanaman)

"""Coba tambahkan kembali:"""

del binatang [2]
print(binatang)

"""Cobain yaa!"""

del tanaman [2]
print(tanaman)

"""Slicing pada String

Karena string mirip dengan list, maka slicing operator [ ]  juga dapat digunakan pada string untuk mengambil isinya atau bahkan substring. Sebuah string utuh bersifat mutable (bisa diubah), namun elemennya bersifat immutable (tidak bisa diubah).
"""

s = "Assalamualaikum Dunia!"
print(s[4]) 		#ambil karakter kelima dari string s
print(s[6:11]) 		#ambil karakter ketujuh hingga sebelas dari string s
s = "Halo Dunia!"	#ubah isi string s menjadi "Halo Dunia!", seharusnya berhasil karena mutable
print (s)

s[5]="d"        #ubah karakter keenam dari string s menjadi "d", seharusnya gagal karena immutable

"""Cobain yaa!




"""

s[6]="d"

"""### **Tuple**

Tuple adalah jenis dari list yang tidak dapat diubah elemennya. Umumnya tuple digunakan untuk data yang bersifat sekali tulis, dan dapat dieksekusi lebih cepat. Tuple didefinisikan dengan kurung dan elemen yang dipisahkan dengan koma.
"""

t = (5,'program', 1+3j)
t

"""Seperti list, kita dapat melakukan slicing, namun pada tuple kita tidak dapat melakukan perubahan:"""

t = (5,'program', 1+3j)
print(t[1])
print(t[0:3])

print(t[0]=10) #Kok gagal, kenapa hayoooooo

a = (5, 6, 7,'aku')#bikin sendiri donk, kreatif dikit napa
print (a)
print(a[1])
del[]

c = ('buku', 4,5,6)
print(c)
print(c[2])
del[]

"""### **Set**

Set adalah kumpulan item bersifat unik dan tanpa urutan (unordered collection). Didefinisikan dengan kurawal dan elemennya dipisahkan dengan koma. Pada Set kita dapat melakukan union dan intersection, sekaligus otomatis melakukan penghapusan data duplikat.
"""

a = {1,2,2,3,3,3}
print(a)

b = { 4,9,2,6,6}
print(b)

"""Karena set bersifat unordered, maka kita tidak bisa mengambil sebagian data / elemen datanya menggunakan proses slicing."""

a = {1,2,3}
print(a[1])

"""### **Dictionary**

Dictionary pada Python adalah kumpulan pasangan kunci-nilai (pair of key-value) yang bersifat tidak berurutan. Dictionary dapat digunakan untuk menyimpan data kecil hingga besar. Untuk mengakses datanya, kita harus mengetahui kuncinya (key). Pada Python, dictionary didefinisikan dengan kurawal dan tambahan definisi berikut:

1. Setiap elemen pair key-value dipisahkan dengan koma (,).
2. Key dan Value dipisahkan dengan titik dua (:).
3. Key dan Value dapat berupa tipe variabel/obyek apapun.
"""

d = {1:'value','key':2}
print(type(d))

d = {1:'value','key':2}
print(type(d))
print("d[1] = ", d[1]);
print("d['key'] = ", d['key']);

"""Dictionary bukan termasuk dalam implementasi urutan (sequences), sehingga tidak bisa dipanggil dengan urutan indeks. Misalnya dalam contoh berikut dicoba dengan indeks 2, tetapi menghasilkan error (KeyError) karena tidak ada kunci (key) 2:"""

d = {1:'value','key':2}
print(type(d))
print("d[1] = ", d[1]);
print("d['key'] = ", d['key']);

# Nyobain error
print("d[2] = ", d[2]);

#bikin versimu sendiri yaaa

d = {1:'value','key':4}
print(type(d))
print("d[1] = ", d[1]);
print("d['key'] = ", d['key']);

"""### **Konversi Struktur Data**

Fungsi untuk mengubah/konversi struktur data:

a. list() : untuk mengubah menjadi list

b. tuple() : untuk mengubah menjadi tuple

c. set() : untuk mengubah menjadi set

d. dict() : untuk mengubah menjadi dictonary

Contoh:
"""

list1 = [1,2,3,4,5]
list2 = ["satu","dua","tiga","empat","lima"]
print("data = ", list1 , ",type =", type(list1))

# Mengkonversi struktur data list
kon_tuple = tuple(list1)
kon_set = set(list1)
kon_dict = dict(zip(list2,list1))

# Melihat data yang telah dikonversi
print(kon_tuple)
print(kon_set)
print(kon_dict)

"""Nah sampai sini, coba kamu tulis pemahaman kamu tentang List, Tuple, Set, dan Dictionary, tulis pake bahasa kamu sendiri ya:

List

Dalam list angka yang ditulis harus berurutan tetapi tidak berurut tipe data dan bisa dicampur penulisannya. Jika ingin menambah data dengan menuliskan append dan jika ingin menghapus data menuliskan del.

Tuple

Kumpulan list yang tidak bisa diubah elemennya tetapi masih bisa memanggil salah satu anggota yang diinginkan dalam list

Set

Set adalah List yang unik bebas pengurutan dan hasilnya bisa terurut sendiri jika ada yang dobel maka hanya satu elemen saja yang akan muncul

Dictionary

Bisa untuk menyimpan data dari yang kecil sampai besar, tetapi harus disebutkan nilai kuncinya terlebih dahulu agar muncul

#**Udah Dulu Ya**

Alhamdulillah
"""